#!/bin/bash
PLATFORM="$1"

if [ -z "$PLATFORM" ]; then
	echo "Usage: $0 PLATFORM"
	echo "  PLATFORM: PLATFORM_WEB, PLATFORM_DESKTOP"
	exit 1
fi

echo "Monitoring src and include folders for changes..."
(
	find src include -type f -name '*.cpp'
	find . -type f -name 'main.cpp'
) | entr -rcs "make PLATFORM=$PLATFORM"
